eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: naresh
spring:
  cloud:
    config:
      override-system-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/quizapp
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
