server:
  port: 8084

spring:

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: scoreGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: scorePayload:com.naresh.PlayerScore_Service.kafka.ScorePayload